In [1]:
import torch
from torch import nn
from transformers.models.bert import BertModel, BertTokenizer, BertForMaskedLM

In [2]:
model_type = 'bert-base-uncased'

In [4]:
tokenizer = BertTokenizer.from_pretrained(model_type)

In [5]:
bert = BertModel.from_pretrained(model_type)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [6]:
mlm = BertForMaskedLM.from_pretrained(model_type, output_hidden_states=True)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [8]:
  # (pooler): BertPooler(
  #   (dense): Linear(in_features=768, out_features=768, bias=True)
  #   (activation): Tanh()
  # )
bert

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          

In [ ]:
# 在最后的结尾不一样 也就是head的部分

In [10]:
# 最后一层不一样
  # (cls): BertOnlyMLMHead(
  #   (predictions): BertLMPredictionHead(
  #     (transform): BertPredictionHeadTransform(
  #       (dense): Linear(in_features=768, out_features=768, bias=True)
  #       (transform_act_fn): GELUActivation()
  #       (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
  #     )
  #     (decoder): Linear(in_features=768, out_features=30522, bias=True)
  #   )
  # )
mlm

BertForMaskedLM(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=Tr

In [11]:
text = ("After Abraham Lincoln won the November 1860 presidential "
        "election on an anti-slavery platform, an initial seven "
        "slave states declared their secession from the country "
        "to form the Confederacy. War broke out in April 1861 "
        "when secessionist forces attacked Fort Sumter in South "
        "Carolina, just over a month after Lincoln's "
        "inauguration.")

In [13]:
inputs = tokenizer(text, return_tensors='pt')
inputs

{'input_ids': tensor([[  101,  2044,  8181,  5367,  2180,  1996,  2281,  7313,  4883,  2602,
          2006,  2019,  3424,  1011,  8864,  4132,  1010,  2019,  3988,  2698,
          6658,  2163,  4161,  2037, 22965,  2013,  1996,  2406,  2000,  2433,
          1996, 18179,  1012,  2162,  3631,  2041,  1999,  2258,  6863,  2043,
         22965,  2923,  2749,  4457,  3481,  7680,  3334,  1999,  2148,  3792,
          1010,  2074,  2058,  1037,  3204,  2044,  5367,  1005,  1055, 17331,
          1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [14]:
inputs['input_ids'].shape

torch.Size([1, 62])

In [15]:
' '.join(tokenizer.convert_ids_to_tokens(inputs['input_ids'][0]))

"[CLS] after abraham lincoln won the november 1860 presidential election on an anti - slavery platform , an initial seven slave states declared their secession from the country to form the confederacy . war broke out in april 1861 when secession ##ist forces attacked fort sum ##ter in south carolina , just over a month after lincoln ' s inauguration . [SEP]"

### 2. masking
- 对于mlm的一个任务 它是有监督的

In [17]:
inputs['labels'] = inputs['input_ids'].detach().clone()
inputs['labels']

tensor([[  101,  2044,  8181,  5367,  2180,  1996,  2281,  7313,  4883,  2602,
          2006,  2019,  3424,  1011,  8864,  4132,  1010,  2019,  3988,  2698,
          6658,  2163,  4161,  2037, 22965,  2013,  1996,  2406,  2000,  2433,
          1996, 18179,  1012,  2162,  3631,  2041,  1999,  2258,  6863,  2043,
         22965,  2923,  2749,  4457,  3481,  7680,  3334,  1999,  2148,  3792,
          1010,  2074,  2058,  1037,  3204,  2044,  5367,  1005,  1055, 17331,
          1012,   102]])

In [18]:
mask = torch.rand(inputs['input_ids'].shape) < 0.15
mask

tensor([[False, False, False, False, False, False, False, False, False,  True,
         False,  True, False, False,  True, False, False, False, False, False,
         False, False, False, False,  True, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False]])

In [19]:
sum(mask[0])

tensor(4)

In [20]:
mask_arr = (torch.rand(inputs['input_ids'].shape) < 0.15) \
        * (inputs['input_ids'] != 101) \
        * (inputs['input_ids'] != 102)

In [21]:
mask_arr

tensor([[False, False, False, False, False, False, False, False, False, False,
         False,  True, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False,  True, False, False, False,  True, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False,  True,  True, False, False, False, False, False, False,
         False, False]])

In [22]:
sum(mask_arr[0])

tensor(5)

In [23]:
selection = torch.flatten(mask_arr[0].nonzero()).tolist()
selection

[11, 33, 37, 52, 53]

In [24]:
tokenizer.special_tokens_map

{'unk_token': '[UNK]',
 'sep_token': '[SEP]',
 'pad_token': '[PAD]',
 'cls_token': '[CLS]',
 'mask_token': '[MASK]'}

In [25]:
tokenizer.vocab['[MASK]']

103

In [ ]:
# 最后的label是有监督学习的lable

In [26]:
inputs['input_ids'][0, selection] = 103
inputs

{'input_ids': tensor([[  101,  2044,  8181,  5367,  2180,  1996,  2281,  7313,  4883,  2602,
          2006,   103,  3424,  1011,  8864,  4132,  1010,  2019,  3988,  2698,
          6658,  2163,  4161,  2037, 22965,  2013,  1996,  2406,  2000,  2433,
          1996, 18179,  1012,   103,  3631,  2041,  1999,   103,  6863,  2043,
         22965,  2923,  2749,  4457,  3481,  7680,  3334,  1999,  2148,  3792,
          1010,  2074,   103,   103,  3204,  2044,  5367,  1005,  1055, 17331,
          1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'labels': tensor([

In [33]:
' '.join(tokenizer.convert_ids_to_tokens(inputs['input_ids'][0]))

"[CLS] after abraham lincoln won the november 1860 presidential election on [MASK] anti - slavery platform , an initial seven slave states declared their secession from the country to form the confederacy . [MASK] broke out in [MASK] 1861 when secession ##ist forces attacked fort sum ##ter in south carolina , just [MASK] [MASK] month after lincoln ' s inauguration . [SEP]"

In [34]:
' '.join(tokenizer.convert_ids_to_tokens(inputs['labels'][0]))

"[CLS] after abraham lincoln won the november 1860 presidential election on an anti - slavery platform , an initial seven slave states declared their secession from the country to form the confederacy . war broke out in april 1861 when secession ##ist forces attacked fort sum ##ter in south carolina , just over a month after lincoln ' s inauguration . [SEP]"

### 3. forward and calculate loss

In [27]:
mlm.eval()
with torch.no_grad():
    output = mlm(**inputs)

In [28]:
output.keys()

odict_keys(['loss', 'logits', 'hidden_states'])

In [29]:
output.logits

tensor([[[ -7.3523,  -7.2794,  -7.3387,  ...,  -6.5167,  -6.4689,  -4.4870],
         [-12.1825, -12.0755, -12.2893,  ..., -11.3469, -10.8439,  -8.7961],
         [ -6.3229,  -6.4907,  -5.9838,  ...,  -6.3363,  -6.1561,  -5.3578],
         ...,
         [ -1.6100,  -1.4929,  -1.5345,  ...,  -0.9445,  -0.8365,  -7.6637],
         [-14.1013, -14.0902, -14.0821,  ..., -11.1695, -11.5065,  -9.9498],
         [-11.1578, -11.6337, -11.1879,  ..., -10.9531,  -8.6970,  -9.5847]]])

In [30]:
output.loss

tensor(0.7166)

In [31]:
len(output['hidden_states'])

13

In [32]:
output['hidden_states'][-1]

tensor([[[-0.3520,  0.0494, -0.3136,  ..., -0.2456, -0.1159,  0.3746],
         [-0.7454, -0.0286,  0.1705,  ..., -0.5019,  0.1807,  0.5617],
         [-0.6919,  1.0039, -0.6699,  ..., -0.5773, -0.3033,  0.3647],
         ...,
         [-0.4524,  0.6711, -0.5974,  ..., -0.9454, -0.5390,  1.3375],
         [ 0.5631, -0.0014, -0.3670,  ...,  0.2012, -0.6400, -0.1903],
         [-0.5298, -0.3617, -0.9992,  ..., -0.1650, -0.4641,  0.2915]]])

### 4. from scratch

In [35]:
mlm.cls(output['hidden_states'][-1])

tensor([[[ -7.3523,  -7.2794,  -7.3387,  ...,  -6.5167,  -6.4689,  -4.4870],
         [-12.1825, -12.0755, -12.2893,  ..., -11.3469, -10.8439,  -8.7961],
         [ -6.3229,  -6.4907,  -5.9838,  ...,  -6.3363,  -6.1561,  -5.3578],
         ...,
         [ -1.6100,  -1.4929,  -1.5345,  ...,  -0.9445,  -0.8365,  -7.6637],
         [-14.1013, -14.0902, -14.0821,  ..., -11.1695, -11.5065,  -9.9498],
         [-11.1578, -11.6337, -11.1879,  ..., -10.9531,  -8.6970,  -9.5847]]],
       grad_fn=<ViewBackward0>)

In [36]:
output.logits

tensor([[[ -7.3523,  -7.2794,  -7.3387,  ...,  -6.5167,  -6.4689,  -4.4870],
         [-12.1825, -12.0755, -12.2893,  ..., -11.3469, -10.8439,  -8.7961],
         [ -6.3229,  -6.4907,  -5.9838,  ...,  -6.3363,  -6.1561,  -5.3578],
         ...,
         [ -1.6100,  -1.4929,  -1.5345,  ...,  -0.9445,  -0.8365,  -7.6637],
         [-14.1013, -14.0902, -14.0821,  ..., -11.1695, -11.5065,  -9.9498],
         [-11.1578, -11.6337, -11.1879,  ..., -10.9531,  -8.6970,  -9.5847]]])

In [37]:
last_hidden_state = output['hidden_states'][-1]

In [38]:
last_hidden_state.shape

torch.Size([1, 62, 768])

In [39]:
mlm.eval()
with torch.no_grad():
    transformed = mlm.cls.predictions.transform(last_hidden_state)
    print(transformed.shape)
    logits = mlm.cls.predictions.decoder(transformed)
    print(logits.shape)
logits

torch.Size([1, 62, 768])
torch.Size([1, 62, 30522])


tensor([[[ -7.3523,  -7.2794,  -7.3387,  ...,  -6.5167,  -6.4689,  -4.4870],
         [-12.1825, -12.0755, -12.2893,  ..., -11.3469, -10.8439,  -8.7961],
         [ -6.3229,  -6.4907,  -5.9838,  ...,  -6.3363,  -6.1561,  -5.3578],
         ...,
         [ -1.6100,  -1.4929,  -1.5345,  ...,  -0.9445,  -0.8365,  -7.6637],
         [-14.1013, -14.0902, -14.0821,  ..., -11.1695, -11.5065,  -9.9498],
         [-11.1578, -11.6337, -11.1879,  ..., -10.9531,  -8.6970,  -9.5847]]])

In [40]:
output.loss

tensor(0.7166)

### 5. loss and translate

In [41]:
ce = nn.CrossEntropyLoss()

In [42]:
logits.shape

torch.Size([1, 62, 30522])

In [43]:
inputs['labels'].shape

torch.Size([1, 62])

In [44]:
inputs['labels'][0].view(-1).shape

torch.Size([62])

In [45]:
ce(logits[0], inputs['labels'][0].view(-1))

tensor(0.7166)

In [46]:
torch.argmax(logits[0], dim=1)

tensor([ 1012,  2044,  8181,  5367,  2180,  1996,  2281,  7313,  4883,  2602,
         2006,  2019,  3424,  1011,  8864,  4132,  1010,  2019,  3988,  2698,
         6658,  2163,  4161,  2037, 22965,  2013,  1996,  2406,  2000,  2433,
         1996, 18179,  1012,  4808, 12591,  2034,  1999,  2285,  6863,  2043,
        22965,  2923,  2749,  4457,  3481,  7680,  3334,  1999,  2148,  3792,
         1010,  2074,  2028,  1037,  3204,  2044,  5367,  1005,  1055, 17331,
         1012,  1055])

In [47]:
' '.join(tokenizer.convert_ids_to_tokens(inputs['input_ids'][0]))

"[CLS] after abraham lincoln won the november 1860 presidential election on [MASK] anti - slavery platform , an initial seven slave states declared their secession from the country to form the confederacy . [MASK] broke out in [MASK] 1861 when secession ##ist forces attacked fort sum ##ter in south carolina , just [MASK] [MASK] month after lincoln ' s inauguration . [SEP]"

In [48]:
' '.join(tokenizer.convert_ids_to_tokens(torch.argmax(logits[0], dim=1)))

". after abraham lincoln won the november 1860 presidential election on an anti - slavery platform , an initial seven slave states declared their secession from the country to form the confederacy . violence erupted first in december 1861 when secession ##ist forces attacked fort sum ##ter in south carolina , just one a month after lincoln ' s inauguration . s"

In [49]:
' '.join(tokenizer.convert_ids_to_tokens(inputs['labels'][0]))

"[CLS] after abraham lincoln won the november 1860 presidential election on an anti - slavery platform , an initial seven slave states declared their secession from the country to form the confederacy . war broke out in april 1861 when secession ##ist forces attacked fort sum ##ter in south carolina , just over a month after lincoln ' s inauguration . [SEP]"